MindU_I2/MindU_I2/Controllers/ArtsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MindU_I2.Models;

namespace MindU_I2.Controllers
{
    public class ArtsController : Controller
    {
        private MindUEntities db = new MindUEntities();

        // GET: Arts
        public ActionResult Index(string name, string category, int page = 0)
        {
            const int pageSize = 10;
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "Please choose category", Value = "Please choose category" });
            items.Add(new SelectListItem { Text = "Art Gallery", Value = "Art Gallery" });
            items.Add(new SelectListItem { Text = "Art Museum", Value = "Art Museum" });
            items.Add(new SelectListItem { Text = "Art School", Value = "Art School" });
            ViewBag.defaultSelect = "Please choose category";
            ViewBag.selectList = items;
            if (name != null && category != "Please choose category")
            {
                var count = db.Arts.Where(x => x.name.Contains(name) && x.category.Equals(category)).ToList().Count();
                var data = db.Arts.Where(x => x.name.Contains(name) && x.category.Equals(category)).OrderBy(s => s.aid).Skip(page * pageSize).Take(pageSize).ToList();
                this.ViewBag.MaxPage = (count / pageSize) - (count % pageSize == 0 ? 1 : 0);
                this.ViewBag.Page = page;
                return View(data);
            }
            else
                if (name == null && category != "Please choose category" && category != null)
            {
                var count = db.Arts.Where(x => x.category.Equals(category)).ToList().Count();
                var data = db.Arts.Where(x => x.category.Equals(category)).OrderBy(s => s.aid).Skip(page * pageSize).Take(pageSize).ToList();
                this.ViewBag.MaxPage = (count / pageSize) - (count % pageSize == 0 ? 1 : 0);
                this.ViewBag.Page = page;
                return View(data);
            }
            else
                if (name != null && category == "Please choose category")
            {
                var count = db.Arts.Where(x => x.name.Contains(name)).ToList().Count();
                var data = db.Arts.Where(x => x.name.Contains(name)).OrderBy(s => s.aid).Skip(page * pageSize).Take(pageSize).ToList();
                this.ViewBag.MaxPage = (count / pageSize) - (count % pageSize == 0 ? 1 : 0);
                this.ViewBag.Page = page;
                return View(data);
            }
            else
            {
                var count = db.Arts.ToList().Count();
                var data = db.Arts.OrderBy(s => s.aid).Skip(page * pageSize).Take(pageSize).ToList();
                this.ViewBag.MaxPage = (count / pageSize) - (count % pageSize == 0 ? 1 : 0);
                this.ViewBag.Page = page;
                return View(data);
            }
        }

        // GET: Arts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Art arts = db.Arts.Find(id);
            if (arts == null)
            {
                return HttpNotFound();
            }
            return View(arts);
        }

        public ActionResult ArtSchool()
        {
            return View();
        }

        public ActionResult Museum()
        {
            return View();
        }

        public ActionResult ArtGallery()
        {
            return View();
        }
        public ActionResult ArtCard()
        {
            return View();
        }

        public string Like(int id)
        {
            ArtRating update = db.ArtRatings.ToList().Find(u => u.rid == id);
            update.likes += 1;
            db.SaveChanges();
            return update.likes.ToString();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MindU_I2/MindU_I2/Controllers/HomeController.cs
using MindU_I2.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MindU_I2.Controllers
{
    public class HomeController : Controller
    {
        private MindUEntities db = new MindUEntities();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {

            return View();
        }
        public ActionResult HelpLine()
        {
            return View();
        }

        public ActionResult Credential()
        {
            var name = Request["password"];
            var btn = Request["button"];
            if (name == "073")
            {
                return RedirectToAction("Index");
            }
            ViewBag.Message = "Please enter password";
            return View();
        }

        [HttpPost]
        public ActionResult Result(RSInput input)
        {
            //initialise the models and ViewBag values that would be returned to the view.
            List<Art> arts = null;
            List<Sport> sports = null;
            ViewBag.needPH = false;
            ViewBag.needInfo = false;

            if (input.likeArt == true) {
            //get a list of art ratings
            List<ArtRating> aRatings = db.ArtRatings.ToList();
            //get the top-3 aids based on the no. of likes
            var aIds = aRatings.OrderByDescending(r => r.likes).Select(r => r.aid).Take(3).ToList();
            //find the top-3 art items from the arts table
            arts = db.Arts.Where(a => aIds.Contains(a.aid)).ToList();
            }
            if (input.likeSport) {

                //get a list of sport ratings
                List<SportRating> sRatings = db.SportRatings.ToList();
                //get the top-3 sids based on the no. of likes
                var sIds = sRatings.OrderByDescending(r => r.likes).Select(r => r.sid).Take(3).ToList();
                //find the top-3 sport items from the arts table
                sports = db.Sports.Where(s => sIds.Contains(s.sid)).ToList();
            }
            if (input.needPH == true) {
                ViewBag.needPH = true;
            }
            if (input.needInfo == true)
            {
                ViewBag.needInfo = true;
            }
            //return a tuple containing two models back to the view
            return View(Tuple.Create(arts, sports));
        }
    }

}

MindU_I2/MindU_I2/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MindU_I2.Models;
using System.Net;
using System.IO;
using Newtonsoft.Json;

namespace MindU_I2.Controllers
{
    public class ServicesController : Controller
    {

  
        public ActionResult ConditionsInfo()
        {
            return View();
        }

        public ActionResult MentalHealthContext()
        {
            return View();
        }

        public ActionResult Tips()
        {
            return View();
        }

        public ActionResult CategoryInfo()
        {
            return View();
        }

        public ActionResult YoungPeopleMentalHealth()
        {
            return View();
        }    
        public ActionResult Search(string category)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "Please choose category", Value = "Please choose category" });
            items.Add(new SelectListItem { Text = "Psychological Consultant", Value = "Psychological Consultant" });
            items.Add(new SelectListItem { Text = "Psychological Clinic", Value = "Psychological Clinic" });
            items.Add(new SelectListItem { Text = "Psychologist", Value = "Psychologist" });
            ViewBag.defaultSelect = "Please choose category";
            ViewBag.selectList = items;
            // Display SearchResult.html page that shows results associated with selected category.
            string apiKey = "AIzaSyC-XG2JrTbessPRoSMRbasmtCwBY8oR2iI";
            var venues = new List<Venue>();
            if (category == null)
            {
                ViewBag.result = 0;
                return View(venues);

            }
            if (category.Contains(" "))
            {
                category.Replace(" ", "+");
            }
            var request = WebRequest.Create("https://maps.googleapis.com/maps/api/place/textsearch/json?query=" + category + "+in+Vic" + "&key=" + apiKey);
            HttpWebResponse response = (HttpWebResponse)request.GetResponse();
            Stream dataStream = response.GetResponseStream();
            StreamReader reader = new StreamReader(dataStream);
            string responseString = reader.ReadToEnd();
            dynamic jsonData = JsonConvert.DeserializeObject(responseString);
            //var venues = new List<Venue>();
            if (jsonData.results == null)
            {
                ViewBag.result = 1;
                return View(venues);
            }
            foreach (var item in jsonData.results)
            {
                string ratingx = item.rating;
                if (ratingx.Contains("5"))
                {
                    venues.Add(new Venue
                    {
                        name = item.name,
                        formatted_address = item.formatted_address,
                        rating = item.rating,
                        place_id = item.place_id,
                        lat = item.geometry.location.lat,
                        lng = item.geometry.location.lng
                    });
                }
            }

            foreach (var venue in venues)
            {
                request = WebRequest.Create("https://maps.googleapis.com/maps/api/place/details/json?placeid=" + venue.place_id + "&fields=formatted_phone_number,website&key=" + apiKey);
                response = (HttpWebResponse)request.GetResponse();
                dataStream = response.GetResponseStream();
                reader = new StreamReader(dataStream);
                responseString = reader.ReadToEnd();
                jsonData = JsonConvert.DeserializeObject(responseString);
                venue.formatted_phone_number = jsonData["result"]["formatted_phone_number"];
                venue.website = jsonData["result"]["website"];

            }
            return View(venues);
        }
        }
    }

MindU_I2/MindU_I2/Controllers/SportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MindU_I2.Models;

namespace MindU_I2.Controllers
{
    public class SportsController : Controller
    {
        private MindUEntities db = new MindUEntities();


        // GET: Sports
        public ActionResult Index(string name, string category, int page = 0)
        {
            const int pageSize = 10;
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "Please choose category", Value = "Please choose category" });
            items.Add(new SelectListItem { Text = "Yoga", Value = "Yoga" });
            items.Add(new SelectListItem { Text = "Pilates", Value = "Pilates" });
            items.Add(new SelectListItem { Text = "Tai Chi", Value = "Tai Chi" });
            items.Add(new SelectListItem { Text = "Fitness Center", Value = "Fitness Center" });
            items.Add(new SelectListItem { Text = "Swimming Complex", Value = "Swimming Complex" });
            ViewBag.defaultSelect = "Please choose category";
            ViewBag.selectList = items;
            if (name != null && category != "Please choose category")
            {
                var count = db.Sports.Where(x => x.name.Contains(name) && x.category.Equals(category)).ToList().Count();
                var data = db.Sports.Where(x => x.name.Contains(name) && x.category.Equals(category)).OrderBy(s => s.sid).Skip(page * pageSize).Take(pageSize).ToList();
                this.ViewBag.MaxPage = (count / pageSize) - (count % pageSize == 0 ? 1 : 0);
                this.ViewBag.Page = page;
                return View(data);
            }
            else
                if (name == null && category != "Please choose category" && category != null)
            {
                var count = db.Sports.Where(x => x.category.Equals(category)).ToList().Count();
                var data = db.Sports.Where(x => x.category.Equals(category)).OrderBy(s => s.sid).Skip(page * pageSize).Take(pageSize).ToList();
                this.ViewBag.MaxPage = (count / pageSize) - (count % pageSize == 0 ? 1 : 0);
                this.ViewBag.Page = page;
                return View(data);
            }
            else
                if (name != null && category == "Please choose category")
            {
                var count = db.Sports.Where(x => x.name.Contains(name)).ToList().Count();
                var data = db.Sports.Where(x => x.name.Contains(name)).OrderBy(s => s.sid).Skip(page * pageSize).Take(pageSize).ToList();
                this.ViewBag.MaxPage = (count / pageSize) - (count % pageSize == 0 ? 1 : 0);
                this.ViewBag.Page = page;
                return View(data);
            }
            else
            {
                var count = db.Sports.ToList().Count();
                var data = db.Sports.OrderBy(s => s.sid).Skip(page * pageSize).Take(pageSize).ToList();
                this.ViewBag.MaxPage = (count / pageSize) - (count % pageSize == 0 ? 1 : 0);
                this.ViewBag.Page = page;
                return View(data);
            }
        }

        public ActionResult Yoga()
        {
            return View();
        }

        public ActionResult TaiChi()
        {
            return View();
        }

        public ActionResult Swimming()
        {
            return View();
        }

        public ActionResult Pilates()
        {
            return View();
        }

        public ActionResult Fitness()
        {
            return View();
        }

        public string Like(int id)
        {
            SportRating update = db.SportRatings.ToList().Find(u => u.rid == id);
            update.likes += 1;
            db.SaveChanges();
            return update.likes.ToString();
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MindU_I2/MindU_I2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>
<!-- Page Content -->
<div class="container">
    <section class="about" id="about">
        <!-- Page Heading/Breadcrumbs -->
        <div>
            <ol class="breadcrumb" style="background-color:transparent;">
                <li class="breadcrumb-item">
                    <a href="@Url.Action("index", "Home")">
                        <img class="active" src="@Url.Content("~/Images/home_icon2.png")">
                    </a>
                </li>
                <li class="breadcrumb-item active">About MindVictoria</li>
            </ol>
        </div>
        <!-- Intro Content -->
        <div class="row">
            <div class="col-lg-7 col-md-12 col-sm-12">
                <h2 class="about_h"> MindVictora – For the international students by international students.</h2>
                <p class="about_font">  MindVictoria  project is to help improve the mental health of the international students in Victoria, Australia. It is operated by international students for the international students. It aims to promote mental wellbeing of international students through arts and sports.</p>
                <p class="about_font">
                    Some of our services also include professional help, mental health articles along with other information to help international students who are mentally stressed, anxious and seeking help.
                </p>
            </div>
            <div class="col-lg-5 col-md-12 col-sm-12">
                <img src="@Url.Content("~/Images/banners/about_us.jpg")" alt="About us">
            </div>
        </div>
    </section>
    <!--Acknowledge-->
    <h2 class="text-center">
        Acknowledgement
    </h2>
    <div class="row text-center">
        <hr>
        <h3>Data Source Details</h3>
        <hr>
        <div class="col-lg-4 col-md-4 col-sm-6">
            <img src="@Url.Content("~/Images/sources_logos/data_sources/1.png")">
        </div>
        <div class="col-lg-4 col-md-4 col-sm-6">
            <img src="@Url.Content("~/Images/sources_logos/data_sources/2.png")">
        </div>
        <div class="col-lg-4 col-md-4 col-sm-6">
            <img src="@Url.Content("~/Images/sources_logos/data_sources/3.png")">
        </div>
    </div>
    <hr>
    <div class="row text-center" style="padding-top:5%;">
        <hr>
        <h3>Images Source Details</h3>
        <hr>
        <div class="row" style="padding-top:1%;">
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="active" src="@Url.Content("~/Images/sources_logos/images_sources/1.png")">
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="active" src="@Url.Content("~/Images/sources_logos/images_sources/2.png")">
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="active" src="@Url.Content("~/Images/sources_logos/images_sources/3.png")">
            </div>
        </div>
        <div class="row" style="padding-top:5%;">
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="active" src="@Url.Content("~/Images/sources_logos/images_sources/4.png")">
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="active" src="@Url.Content("~/Images/sources_logos/images_sources/5.png")">
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="active" src="@Url.Content("~/Images/sources_logos/images_sources/6.png")">
            </div>
        </div>
        <div class="row" style="padding-top:5%;">
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="active" src="@Url.Content("~/Images/sources_logos/images_sources/7.png")">
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="active" src="@Url.Content("~/Images/sources_logos/images_sources/8.png")">
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="active" src="@Url.Content("~/Images/sources_logos/images_sources/9.png")">
            </div>
        </div>
        <div class="row" style="padding-top:5%;">
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="active" src="@Url.Content("~/Images/sources_logos/images_sources/10.png")">
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="active" src="@Url.Content("~/Images/sources_logos/images_sources/11.png")">
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="active" src="@Url.Content("~/Images/sources_logos/images_sources/12.png")">
            </div>
        </div>
        <div class="row" style="padding-top:5%;">
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="active" src="@Url.Content("~/Images/sources_logos/images_sources/13.png")">
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="active" src="@Url.Content("~/Images/sources_logos/images_sources/14.png")">
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <img class="active" src="@Url.Content("~/Images/sources_logos/images_sources/15.png")">
            </div>
        </div>
            <hr>
        </div>
    </div>
<!-- /.row -->

MindU_I2/MindU_I2/Views/Home/Credential.cshtml
@{
    Layout = null;
}
<h3 style="text-align:center">@ViewBag.Message</h3>
<form action="/home/credential" method="post">
    <div style="text-align:center; vertical-align:middle">
        <input type="password" style="text-align:center" name="password" />
        <input type="submit" name="button" value="submit" />
    </div>
</form>

MindU_I2/MindU_I2/Views/Home/Index.cshtml
@model MindU_I2.Models.RSInput
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Home";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
@Styles.Render("~/Content/RS_Home.css")
<script>
    $("document").ready(function () {
        $('#service_btn').click(function () {
            $('html, body').animate({
                scrollTop: $(".services_section").offset().top
            }, 2500);
        });
    });
    $("document").ready(function () {
        $('#rs_btn').click(function () {
            $('html, body').animate({
                scrollTop: $(".recommend_system").offset().top
            }, 2500);
        });
    });
    $("document").ready(function () {
        $('#get_start').click(function () {
            $('html, body').animate({
                scrollTop: $(".recommend_system").offset().top
            }, 2500);
        });
    });

</script>
<!--banner-->
<header class="masthead text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto" style="margin-top:21%; margin-left:10%;">
                <h1 style="color:white;">
                    <strong>United we stand</strong>
                </h1>
                <h3 style="color:white;">
                    Reaching out for help is not a sign of weakness, it is a sign of strength. When it gets tough, ask for help
                </h3>
                <a id="service_btn" class="btn btn-primary btn-xl">FIND A SERVICE</a>
                <a id="rs_btn" class="btn btn-primary btn-xl">MORE INFO</a>
            </div>
        </div>
    </div>
</header>
<!-- Page Content -->
<!--Section About-->
<section class="about" style="background-color:#F05F40">
    <div class="container">
        <div class="row" style="margin-top:5%;  color:white;">
            <div class="col-lg-12 mx-auto text-center">
                <h1 class="section-heading text-white">WHO WE ARE</h1>
                <div class="col-md-12" align="center">
                    <h1 style="font-size:x-large">
                        MindVictora – For the international students by the international students.
                    </h1>
                    <p style="font-size:larger; text-align:justify;">
                        MindVictoria is a project to help improve the mental health of the international students in Victoria, Australia. It is operated by international students for the international students.
                    </p>
                    <p style="font-size:larger; text-align:justify;">
                        MindVictoria aims to promote mental wellbeing of international students through arts and sports.
                        Some of our services also include professional help, mental health articles along with other information to help international students who are mentally stressed, anxious and seeking help.
                    </p>
                    <button id="get_start" class="btn btn-light btn-xl" style="margin-bottom:5%;">Get Started!</button>
                </div>
            </div>
        </div>
    </div>
</section>
<!--Section Services-->
<section class="services_section" id="services">
    <div class="row">
        <div class="col-lg-3 col-md-6 services-item">
            <div class="b_card-text">
                <a href='@Url.Action("Search", "Services")'>
                    <img src="@Url.Content("~/Images/boxes/PH.png")" alt="conditions">
                </a>
                <h3 class="b_card-title">
                    Professional Help
                </h3>
                <div class="b_card-body">
                    <p class="b_card-text">
                        locate consultants, clinics and other mental health institutions.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 services-item">
            <div class="b_card-text">
                <a href='@Url.Action("Index", "Arts")'>
                    <img src="@Url.Content("~/Images/boxes/art.png")" alt="conditions">
                </a>
                <h3 class="b_card-title">
                    Art Spaces
                </h3>
                <div class="b_card-body">
                    <p class="b_card-text">
                        Find the finest art planes in and around Melbourne.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 services-item">
            <div class="b_card-text">
                <a href='@Url.Action("Index", "Sports")'>
                    <img src="@Url.Content("~/Images/boxes/sport.png")" alt="conditions">
                </a>
                <h3 class="b_card-title">
                    Sports Activities
                </h3>
                <div class="b_card-body">
                    <p class="b_card-text">
                        Physical activities that improve the mental health
                    </p>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 services-item">
            <div class="b_card-text">
                <a href='@Url.Action("Helpline", "Home")'>
                    <img src="@Url.Content("~/Images/boxes/helpline.png")" alt="conditions">
                </a>
                <h3 class="b_card-title">
                    Hotlines
                </h3>
                <div class="b_card-body">
                    <p class="b_card-text">
                        24 hours helplines and emergencies.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
<!--End Section RS-->
<section class="recommend_system col-lg-12" style="background-color:#F05F40; height:72%; width:100%;">
    <br />
    <h2 class="text-center" style="color:#fff">For more info, tell me what you like...</h2>
    <div class="container" style=" background-color:honeydew;  height:68%; width:45%; margin-top:1.8%; margin-bottom:2%; box-shadow:0 4px 8px 0 rgba(255, 255, 255, 0.2), 0 6px 20px 0 rgba(255, 255, 255, 0.19);">
        @using (Html.BeginForm("Result", "Home", FormMethod.Post))
        {
            <div class="form-group">
                <div class="col-lg-12">
                    <h3>Are you seeking professinal help?</h3>
                </div>
                <div class="col-md-12  text-center">
                    <div class="col-md-3  text-center">
                        @Html.RadioButton("needPH", true, false, new { @id = "radio-img-5", @style = "size"})
                        @Html.Label("radio-img-5", new { @class = "Yes" })
                    </div>
                    <div class="col-md-4  text-center">
                        @Html.RadioButton("needPH", false, false, new { @id = "radio-img-6" })
                        @Html.Label("radio-img-6", new { @class = "No" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-12">
                    <h3>Are you an art lover? </h3>
                </div>
                <div class="col-md-12  text-center">
                    <div class="col-md-3">
                        @Html.RadioButton("likeArt", true, false, new { @id = "radio-img-1" })
                        @Html.Label("radio-img-1", new { @class = "Yes" })
                    </div>
                    <div class="col-md-4  text-center">
                        @Html.RadioButton("likeArt", false, false, new { @id = "radio-img-2" })
                        @Html.Label("radio-img-2", new { @class = "No" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-12">
                    <h3>Do you Want to know more about mental health conditions?</h3>
                </div>
                <div class="col-md-12  text-center">
                    <div class="col-md-3 text-center">
                        @Html.RadioButton("needInfo", true, false, new { @id = "radio-img-7" })
                        @Html.Label("radio-img-7", new { @class = "Yes" })
                    </div>
                    <div class="col-md-4  text-center">
                        @Html.RadioButton("needInfo", false, false, new { @id = "radio-img-8" })
                        @Html.Label("radio-img-8", new { @class = "No" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lg-12">
                    <h3>Are you an active person?</h3>
                </div>
                <div class="col-md-12  text-center">
                    <div class="col-md-3  text-center">
                        @Html.RadioButton("likeSport", true, false, new { @id = "radio-img-3" })
                        @Html.Label("radio-img-3", new { @class = "Yes" })
                    </div>
                    <div class="col-md-4  text-center">
                        @Html.RadioButton("likeSport", false, false, new { @id = "radio-img-4" })
                        @Html.Label("radio-img-4", new { @class = "No" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12  text-center">
                    <br />
                    <button type="submit" class="btn btn-primary btn-xl">Submit</button>
                </div>
            </div>
        }
    </div>
</section>
<div class="container">

</div>